
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int obracke = 2;
  public static final int sub = 5;
  public static final int id = 4;
  public static final int greather = 6;
  public static final int setER = 9;
  public static final int question = 13;
  public static final int mult = 14;
  public static final int or = 15;
  public static final int semicolon = 7;
  public static final int EOF = 0;
  public static final int cbracke = 3;
  public static final int sum = 11;
  public static final int error = 1;
  public static final int id_setER = 8;
  public static final int concat = 12;
  public static final int specialSetER = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "obracke",
  "cbracke",
  "id",
  "sub",
  "greather",
  "semicolon",
  "id_setER",
  "setER",
  "specialSetER",
  "sum",
  "concat",
  "question",
  "mult",
  "or"
  };
}

