/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

/**
 *
 * @author Robin
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        menuitmsave = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuitmsaveas = new javax.swing.JMenuItem();
        menuhelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ExRegan USAC");
        setPreferredSize(new java.awt.Dimension(1280, 600));
        setResizable(false);

        menufile.setText("Archivo");

        menuitmsave.setText("Abrir");
        menuitmsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitmsaveActionPerformed(evt);
            }
        });
        menufile.add(menuitmsave);

        jMenuItem2.setText("Guardar");
        menufile.add(jMenuItem2);

        menuitmsaveas.setText("Guardar como");
        menufile.add(menuitmsaveas);

        menubar.add(menufile);

        menuhelp.setText("Ayuda");
        menubar.add(menuhelp);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitmsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitmsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuitmsaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenu menufile;
    private javax.swing.JMenu menuhelp;
    private javax.swing.JMenuItem menuitmsave;
    private javax.swing.JMenuItem menuitmsaveas;
    // End of variables declaration//GEN-END:variables
}
