
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Logic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOKEN_NUMBER = 8;
  public static final int TOKEN_SUB = 4;
  public static final int TOKEN_DIV = 5;
  public static final int EOF = 0;
  public static final int TOKEN_PRINT = 7;
  public static final int TOKEN_MULT = 6;
  public static final int error = 1;
  public static final int TOKEN_ADD = 3;
  public static final int TOKEN_PUSH = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOKEN_PUSH",
  "TOKEN_ADD",
  "TOKEN_SUB",
  "TOKEN_DIV",
  "TOKEN_MULT",
  "TOKEN_PRINT",
  "TOKEN_NUMBER"
  };
}

